exclude:
  - /vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - '*.gemspec'
  - work.html
  - liquids
keep_files:
  - CNAME
  - .git
  - .gitignore
title: Universal Functional
subtitle: Computing is Exciting
url: null
baseurl: /blog
cover: img/cover.png
logo: img/logo.png
markdown: kramdown
descriptions:
  - cat: jekyll
    desc: Posts describing Jekyll setup techniques.
  - cat: dummy
    desc: 'Just some placeholder posts, lorem ipsum and the rest.'
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-paginate
