exclude:
  - /vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - '*.gemspec'
  - work.html
  - left-over
keep_files:
  - CNAME
  - .git
  - .gitignore
title: Universal Functional
subtitle: Computing is Exciting
url: null
baseurl: ""
cover: img/slider-bg.jpg
logo: img/logo.png
disqus-id: https-apsdft-github-io 
markdown: kramdown
paginate: 4
paginate_path: "/blog/page:num/"
descriptions:
  - cat: jekyll
    desc: Posts describing Jekyll setup techniques.
  - cat: dummy
    desc: 'Just some placeholder posts, lorem ipsum and the rest.'
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-paginate
